learning/learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # Needed To be able to see images in admin dashboard
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls, name='admin'),
                  path('', include(('posts.urls', 'posts'), namespace='posts')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Toma la ruta del archivo multimedia y hace que no lo tome como una ruta de url sino para llegar y abrir el archivo

learning/posts/urls.py
# Django
from django.urls import path
# views
from posts import views

urlpatterns = [
    path(
        route='posts/',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='newpost'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    ]

learning/users/urls.py
# Users.urls
from django.urls import path

from users import views

urlpatterns = [



    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route='singup/',
        view=views.SingupView.as_view(),
        name='singup'
    ),

    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(
            template_name='users/detail.html'
        ),
        name='detail'
    ),

]

learning/users/models.py
from django.contrib.auth.models import User
from django.db import models as m


# Create your models here.
class Profile(m.Model):
    """Proxy model uses Abstract class User and added needed info"""

    user = m.OneToOneField(User, on_delete=m.CASCADE)  # Check Documentation

    # new fields
    website = m.URLField(max_length=250, blank=True)
    biography = m.TextField(blank=True)
    phone_number = m.CharField(max_length=20, blank=True)
    profile_picture = m.ImageField(
        upload_to="users/pictures",
        blank=True,
        null=True
    )
    created = m.DateTimeField(auto_now_add=True)
    modified = m.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username"""
        return self.user.username

learning/users/forms.py
from django import forms

# Models
from django.contrib.auth.models import User

from users.models import Profile


"""
DEPRECATED

class UpdateUser(forms.Form):
    website = forms.URLField(max_length=200, required=True)

    biography = forms.CharField(max_length=256, required=False)

    phone_number = forms.CharField(max_length=20, required=True)

    picture = forms.ImageField(required=False)
    
DEPRECATED
"""

class SingupForm(forms.Form):
    username = forms.CharField(max_length=20, required=True)
    password = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput
    )
    password_confirmation = forms.CharField(
        min_length=8,
        widget=forms.PasswordInput  # El Widget para hacer comprobaciones
    )
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()

    def clean_username(self):
        """Username must be:
        - Unique
        """

        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already taken')
        return username

    def clean(self):
        """Verify password confirmation match"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match')

    def save(self):
        """Create User and Profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')
        
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()
        

learning/users/views.py
# Django
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

# Forms
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, FormView, UpdateView
from users.forms import SingupForm

# Models
from django.contrib.auth.models import User
from users.models import Profile

from  posts.models import Post


class LoginView(auth_views.LoginView):
    # Login View
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class LogoutView(auth_views.LogoutView):
    # Log out View
    pass


class UserDetailView(DetailView, LoginRequiredMixin):
    # User Detail View
    template_name = 'users/detail.html'
    slug_field = 'username' # Como se hara en la queryset
    slug_url_kwarg = 'username' # Como sera llamado desde la URL
    model = User
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add Users Post to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context


class SingupView(FormView):
    # Sing up view
    template_name = "users/singup.html"
    form_class = SingupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        # Save form data
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    # Log in view
    template_name = 'users/update/profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'profile_picture']

    def get_object(self, queryset=None):
        # Return users profile if
        return self.request.user.profile

    def get_success_url(self):
        # Return to Users Profile
        username = self.object.user.username
        return reverse('users:detail', kwargs= {'username': username})




""" DEPRECATED
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            # Redirect to a Success page
            return redirect('posts:feed')
        else:
            # Return to an 'invalid login' error message
            return render(request, 'users/login.html', context={'error': 'Invalid user or password'})
    #    import pdb
    #    pdb.set_trace()
    return render(
        request,
        template_name='users/login.html'
    )


@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')

def singup_view(request):
    if request.method == 'POST':

        form = SingupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('users:login')

        else:
            form = SingupForm()
        return render(request,
                      template_name='users/singup.html',
                      context={'form': form}
                      )
    return render(request, template_name='users/singup.html')

@login_required
def update_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form = UpdateUser(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            profile.website = data['website']
            profile.biography = data['biography']
            profile.phone_number = data['phone_number']
            if data['picture']:
                profile.profile_picture = data['picture']

            profile.save()
            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect(url)
    else:
        form = UpdateUser()
    return render(
        request,
        'users/update/profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form
        }
    )

DEPRECATED
"""

learning/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

learning/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Chiguigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.profile_picture.url }}" alt="@{{ request.user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if request.user == user %}
                        <a href="{% url 'users:update_profile' %}"
                           class="ml-5 btn btn-sm btn-outline-info">
                            Edit profile
                        </a>
                    {% else %}
                        <a href=""
                           class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

     <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

learning/templates/users/login.html
{% extends 'users/base.html' %}


{% block head_content %}
    <title>Login</title>    
{% endblock head_content %}


{% block container %}
    
    {% if form.errors %}
        <p class="alert alert-danger">Your user and password didn't match</p>
    {% endif %}
        
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username", name="username">
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password">
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign In!</button>

    </form>

<p class="mt-4">don't have an account yet? <a href="{% url 'users:singup' %}">Sign Up here.</a></p>

{% endblock container %}

learning/templates/users/singup.html
{% extends 'users/base.html' %}


{% block head_content %}
    <title>Sing Up!</title>    
{% endblock head_content %}


{% block container %}
    
    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}
        
    <form action="{% url 'users:singup' %}" method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username", name="username" required="true">
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Password" name="password"  required="true">
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Confirm password" name="password_confirmation"
                   required="true">
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="First Name", name="first_name"  required="true">
        </div>

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Last Name", name="last_name"  required="true">
        </div>

        <div class="form-group">
            <input class="form-control" type="email" placeholder="Email", name="email" required="true">
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign Up!</button>

    </form>
{% endblock container %}