learning/learning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # Needed To be able to see images in admin dashboard
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls, name='admin'),
                  path('', include(('posts.urls', 'posts'), namespace='posts')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Toma la ruta del archivo multimedia y hace que no lo tome como una ruta de url sino para llegar y abrir el archivo

learning/posts/urls.py
# Django
from django.urls import path
# views
from posts import views

urlpatterns = [
    path(
        route='posts/',
        view=views.PostsFeedView.as_view(),
        name='feed'
    ),

    path(
        route='posts/new/',
        view=views.CreatePostView.as_view(),
        name='newpost'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    ]

learning/users/urls.py
# Users.urls
from django.urls import path

from users import views

urlpatterns = [



    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),

    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route='singup/',
        view=views.SingupView.as_view(),
        name='singup'
    ),

    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
    ),

    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(
            template_name='users/detail.html'
        ),
        name='detail'
    ),

]

learning/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <br><br>
    {% block head_content %}
    <!-- Bloque contenedor con el que se va a inyectar el HTML deseado en este caso posts/feed.html-->
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block container %} 
        <!-- Bloque contenedor con el que se va a inyectar el HTML deseado-->
        {% endblock %}
    </div>

    {% include "pagination.html" %}

</body>
</html>

learning/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed'%}">
            <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.profile_picture %}
                            <img src="{{ request.user.profile.profile_picture.url }}" height="35" class="d-inline-block align-top rounded-circle">
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif  %} 
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:newpost' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout'%}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</nav>

learning/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>